//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IlogicSoftwaresWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id { get; set; }
        public string productid { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public string image { get; set; }
        public string videourl { get; set; }
        public string marca { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string CarTitulo { get; set; }
        public string caracteristicas { get; set; }
        public Nullable<decimal> tempimplement { get; set; }
        public string jumbo { get; set; }
        public string licencia { get; set; }
    }
}
